### ISSUE TITLE
Build error: No such file or directory: 'openblas.tar.gz.part'

### ISSUE THREAD

**Issue by delip** [joschu/cgt#1]
Super excited to try this, but right now stuck on this build error:

```
[100%] Built target cycgt
Traceback (most recent call last):
  File "4build/download_and_build_openblas.py", line 19, in <module>
    shutil.move("{fname}.part".format(fname=fname),"{fname}".format(fname=fname))
  File "/Users/delip/anaconda/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/Users/delip/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/delip/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'openblas.tar.gz.part'
make[2]: *** [OpenBLAS/libopenblas.a] Error 1
make[1]: *** [CMakeFiles/openblas.dir/all] Error 2
make: *** [all] Error 2
```

The makefiles were generated using:
```
cmake .. -DCGT_ENABLE_CUDA=ON
```

**Comment by zxie** [comment]
Think just commenting out the `shutil.move` line avoids this error.

**Comment by delip** [comment]
Perfect. Worked. FYI - one of the tests seem to fail. Is this my env problem?

```
gt.tests.test_imgproc.test_cudnn ... SKIP: CUDNN not enabled. Skipping this test
cgt.tests.test_imgproc.test_cpu_pool ... ok
cgt.tests.test_imgproc.test_im2col ... ok
cgt.tests.test_imgproc.test_lrn ... ok
cgt.tests.test_informative_errors.test_shape_err ... FAIL
cgt.tests.test_linreg.test_linreg ... ok
cgt.tests.test_multi_output.test_multi_output ... ok
cgt.tests.test_par_interp.test_sleeps ... ok
cgt.tests.test_par_interp.test_matmuls ... ok
cgt.tests.test_par_interp.test_update ... ok
cgt.tests.test_scalars.test_scalars('single', 'python') ... ok
cgt.tests.test_scalars.test_scalars('double', 'python') ... ok
cgt.tests.test_scalars.test_scalars('single', 'native') ... ok
cgt.tests.test_scalars.test_scalars('double', 'native') ... ok

======================================================================
ERROR: cgt.tests.test_examples.test_examples('CGT_FLAGS=backend=native python /Users/delip/Softwares/cgt/cgt/tests/../../examples/demo_cifar.py --unittest',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/delip/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/delip/Softwares/cgt/cgt/tests/test_examples.py", line 7, in run_example
    subprocess.check_call(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/delip/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'CGT_FLAGS=backend=native python /Users/delip/Softwares/cgt/cgt/tests/../../examples/demo_cifar.py --unittest' returned non-zero exit status 1

======================================================================
FAIL: cgt.tests.test_informative_errors.test_shape_err
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/delip/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/delip/Softwares/cgt/cgt/tests/test_informative_errors.py", line 24, in test_shape_err
    assert "f = cgt.function([x,y],x+y)" in s.getvalue()
AssertionError:
-------------------- >> begin captured logging << --------------------
root: INFO: Simplification
root: INFO: Device targeting
root: INFO: Build execution graph
--------------------- >> end captured logging << ---------------------
```

**Comment by joschu** [comment]
Fixed the openblas download bug in e72e5a1. thanks for reporting

**Comment by joschu** [comment]
I don't know what's causing the other unit error. Could you add the line "print s.getvalue()" before the assertion failure in test_informative_errors.py?

**Comment by erictzeng** [comment]
Hi John, cool library!

I'm getting the same failure, so here's my output with the requested additional `print`:

````
~/s/cgt ❯❯❯ nosetests
........S...SS..SF.........
======================================================================
FAIL: cgt.tests.test_informative_errors.test_shape_err
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/etzeng/src/cgt/cgt/tests/test_informative_errors.py", line 25, in test_shape_err
    assert "f = cgt.function([x,y],x+y)" in s.getvalue()
AssertionError:
-------------------- >> begin captured stdout << ---------------------
Traceback (most recent call last):
  File "/Users/etzeng/src/cgt/cgt/compilation.py", line 773, in __call__
    instr.fire(self)
  File "/Users/etzeng/src/cgt/cgt/compilation.py", line 493, in fire
    interp.get(self.write_loc))
  File "/Users/etzeng/src/cgt/cgt/core.py", line 777, in call
    return self._func(*args)
  File "/Users/etzeng/src/cgt/cgt/core.py", line 1303, in f
    raise RuntimeError("mismatched shapes %s %s. Note that implicit broadcasting isn't allowed. Use the broadcast(...) function"%(x.shape, y.shape))
RuntimeError: mismatched shapes (3,) (4,). Note that implicit broadcasting isn't allowed. Use the broadcast(...) function


--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Simplification
root: INFO: Device targeting
root: INFO: Build execution graph
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 27 tests in 12.610s

FAILED (SKIP=4, failures=1)
````

I'm on OSX so it could be some potential weirdness across different operating systems.

**Comment by joschu** [comment]
Thanks, I think I know what the problem is now.

**Comment by joschu** [comment]
Fixed
